# Probability and Statistics start

## Mean
## Median
## Mode

In [22]:
import numpy as np
data = [23, 40, 35, 23, 40, 40, 40, 21, 25, 38,]

mean = np.mean(data)
print(mean)

median = np.median(data)
print(median)


32.5
36.5


In [23]:
#detailed mode
from scipy import stats
mode_1 = stats.mode(data)
print(mode_1)

ModeResult(mode=np.int64(40), count=np.int64(4))


In [24]:
#mode
import statistics
mode_2 = statistics.mode(data)
print(mode_2)

40


In [25]:
#more about mean and standard deviation
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60,40])
print("mean: ",np.mean(arr))
print("median: ",np.median(arr))
print("standard deviation: ",np.std(arr))

mean:  35.714285714285715
median:  40.0
standard deviation:  15.90789817951435


##numpy arrays

In [30]:
import numpy as np
a = np.zeros(3)
a

array([0., 0., 0.])

In [27]:
type(a)
type(a[0])

numpy.float64

In [29]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
z.shape

(10,)

In [32]:
z.shape = (10, 1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [34]:
z = np.ones(10)
z


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
z = np.empty(3)
z

array([0., 0., 0.])

In [ ]:
z = np.linspace(2, 10, 5) #states digits from 2 to 10.
z

array([ 2.,  4.,  6.,  8., 10.])

In [38]:
z = np.array([10, 20])
z

array([10, 20])

In [39]:
a_list = [1, 2, 3, 4, 5, 6, 7]
z = np.array([a_list])
z

array([[1, 2, 3, 4, 5, 6, 7]])

In [40]:
type(z)

numpy.ndarray

In [41]:
b_list = [[1,2,3,4,5],[5,6,7,8,9]]
z = np.array([b_list])
z

array([[[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9]]])

In [42]:
?z.shape

Type:        tuple
String form: (1, 2, 5)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.


In [43]:
np.random.seed(0)
z1 = np.random.randint(10, size=6)
z1

array([5, 0, 3, 3, 7, 9])

In [46]:
z1[0]
z1[0:2]
z1[-1]

np.int64(9)

In [47]:
#meaning
z1[0:2]

array([5, 0])

In [1]:
print("End numpy")

End numpy
